---
cli:
  host: "{{ inventory_hostname }}"
  username: admin
  password: cisco123
ansible_network_os: ios
ansible_command_timeout: 18000
upgrade_ios_version: 16.09.06
upgrade_file: "c1100-universalk9_ias.16.09.06.SPA.bin"
upgrade_path: "images/c1100-universalk9_ias.16.09.06.SPA.bin"
router_file: "bootflash:/c1100-universalk9_ias.16.09.06.SPA.bin"
tftp_server_ip: 192.168.12.4
