# Ansible Playbook to reboot Cisco IOS XE Devices
#
---
- name: Reboot Cisco IOS XE Devices
  hosts: all
  connection: network_cli
  gather_facts: no
  vars_files:
    - group_vars/catalyst_vars.yaml

  tasks:
    - name: Issue reload command
      cli_command:
        command: reload
        prompt: 
          - confirm
        answer:
          - y
      register: reload_output

