---
# Ansible Playbook to uploade images to Cisco Devices running IOS XE
# Show running version
#
- name: Display running version on Cisco IOS Devices 
  hosts: all
  connection: network_cli
  gather_facts: no
  vars_files:
    - group_vars/catalyst_vars.yaml
    - group_vars/users.yaml

  tasks:
    - name: Display running version
      ios_facts:
    - debug:
        msg:
        - "Current version is {{ ansible_net_version }}"

