---
# Ansible Playbook to uploade images to Cisco Switches running IOS XE
#
# This play book cleans up unused firmware package files on the flash
#
- name: Cleanup unused firmware package files on Cisco IOS XE Switches
  hosts: ios_xe
  connection: network_cli
  gather_facts: no
  vars_files:
    - ../group_vars/catalyst_vars.yaml
    - ../group_vars/users.yaml

  tasks:
  - name: Run "show version" to check if the switch is in INSTALL mode
    cisco.ios.ios_command:
      commands:
        - show version
    register: version_output

  - name: Parse "show version" output for INSTALL mode
    set_fact:
      in_install_mode: "{{ 'INSTALL' in version_output.stdout[0] }}"

  - name: Display whether the switch is in INSTALL mode
    debug:
      msg: "The switch is in INSTALL mode: {{ in_install_mode }}"

  - name: Fail if the switch is not in INSTALL mode
    fail:
      msg: "The switch is not in INSTALL mode. Operation cannot be proceeded."
    when: in_install_mode == False

  - name: Cleanup using install remove inactive commands
    cli_command:
      command: install remove inactive
      prompt:
        - remove the above files
      answer:
        - y
    register: cleanup_output
