---
# Playbook to configure a reboot EEM on Cisco devices so that interactive prompt is handled by EEM scripts

- name: Display running version on Cisco IOS devices
  hosts: all
  gather_facts: false
  tasks:

    # Task 1: Check whether the device has the same EEM script defined
    - name: Run "show run | inc event.*REBOOT" to check if the switch is in INSTALL mode
      cisco.ios.ios_command:
        commands:
          - "show run | inc event.*REBOOT"
      register: version_output

    - name: Determine the if a REBOOT script exists
      set_fact:
        eem_exist: >
          {% if 'REBOOT' in version_output.stdout[0] %}
            true
          {% else %}
            false
          {% endif %}

    # Task 2: Configure the EEM scripts
    - name: Configure the EEM script by first removing the existing one 
      cisco.ios.ios_config:
        lines:
          - no event manager applet REBOOT
          - event manager applet REBOOT authorization bypass
          - event none
          - action 0001 cli command "enable"
          - action 0002 cli command "term length 0"
          - action 0010 cli command "reload" pattern "confirm"
          - action 0020 cli command "y"
        save_when: always
      when: eem_exist 
        
    - name: Configure the EEM script by first removing the existing one 
      cisco.ios.ios_config:
        lines:
          - event manager applet REBOOT authorization bypass
          - event none
          - action 0001 cli command "enable"
          - action 0002 cli command "term length 0"
          - action 0010 cli command "reload" pattern "confirm"
        save_when: always
      when: not eem_exist 
