---
# Ansible Playbook to reboot Cisco IOS XE Devices
- name: Reboot Cisco IOS XE Devices
  hosts: all
  gather_facts: no

  tasks:
    - name: Issue reload command
      cisco.ios.ios_command:
        commands: "reload in 0"
      register: reload_output

    - name: Display reload output
      debug:
        var: reload_output.stdout

