---
# Playbook to display the running version on Cisco IOS Devices

- name: Display running version on Cisco IOS devices
  hosts: all
  gather_facts: false
  tasks:
    - name: Gather facts from Cisco devices
      cisco.ios.ios_facts:
      register: facts

    - name: Display all gathered facts
      debug:
        var: facts

    - name: Display running version
      debug:
        msg: "Current version is {{ facts.ansible_facts.ansible_net_version }}"

    - name: Override username to survey variable if set  
      set_fact:
        ansible_user: "{{ survey_user }}"
      when: survey_user is defined and survey_user != ""

    - name: Override password to survey variable if set
      set_fact:
        ansible_ssh_pass: "{{ survey_pass }}"
      when: survey_pass is defined and survey_pass != ""

    - name: Display username and password
      debug:
        msg: "Username is {{ ansible_user }}. Password is {{ ansible_ssh_pass }}."
